* This patch should fix the following errors that have been occuring for some   people after the RingBuffer fills up while watching LiveTV.
    ERROR: file I/O problem in 'safe_read()': Bad address
    ERROR: file I/O problem in 'safe_read()': Invalid argument

  It appears to have been related to avformatdecoder/libavformat triggering
  a SEEK_SET in the middle of playback for recordings.  This is fine for
  normal recordings, but when in LiveTV, when the total position in the
  stream exceeds the size of the RingBuffer, RingBuffer::Seek() couldn't
  handle it and would seek off to a bad location, causing safe_read() to fail.


git-svn-id: http://svn.mythtv.org/trunk@5971 4b91aca1-2a1f-0410-a73a-a78f2df169e8